# Generated by Django 5.1.5 on 2025-01-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='content',
            field=models.TextField(default='입력하세요'),
        ),
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='devtools.devtool'),
        ),
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(null=True, upload_to='ideas/'),
        ),
        migrations.AddField(
            model_name='idea',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ideas/thumbnails/'),
        ),
    ]
