# Generated by Django 5.1.5 on 2025-01-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_content_idea_devtool_idea_image_idea_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
