# Generated by Django 5.1.5 on 2025-01-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_remove_idea_wishlist_idea_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='tags',
        ),
        migrations.AddField(
            model_name='ideastar',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
