# Generated by Django 5.1.4 on 2025-01-10 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('star', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('year', models.IntegerField(null=True)),
                ('genre', models.CharField(choices=[('액션', '액션'), ('드라마', '드라마'), ('코믹', '코믹'), ('호러', '호러'), ('로맨스', '로맨스'), ('SF', 'SF')], default='액션', max_length=50)),
                ('pd', models.CharField(max_length=200, null=True)),
                ('actors', models.CharField(max_length=500, null=True)),
                ('running_time', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
